### ISSUE TITLE
Information about the project

### ISSUE THREAD

**Issue by pietro909** [scalajs-react-universe/docs#1]
Hi there,
I came here from [SRI](https://github.com/chandu0101/sri): I'm investigating the possibility of using ScalaJS with React Native for a new project but I can't understand what's going on here :-)

Is there a channel (slack, irc, gitter, pigeon post, ...) where you are discussing it?

Thanks!

**Comment by chandu0101** [comment]
Hi,
      we're still using sri gitter channel , come there if you want to chat ...
